### ISSUE TITLE
If statement

### ISSUE THREAD

**Issue by GerardWalsh** [GerardWalsh/_practice#3]
@Shoki-Shoki At the moment the if statement is checking if we have supplied 4 args, and if not it's printing a message to the terminal. Can you please functionality such that the program exits when 4 are not supplied, not like at the moment where we are still printing the args out, even if 4 are not supplied.

**Comment by GerardWalsh** [comment]
Can you create a new branch from master, add your changes to the branch, create a PR and assign me as a reviewer please?

**Comment by Shoki-Shoki** [comment]
Let me add  exit function .

**Comment by GerardWalsh** [comment]
Cool cool, please slack me when its ready.

**Comment by Shoki-Shoki** [comment]
I have included the function
